export const SHOW_BUILDINGS = "SHOW_BUILDINGS";
export const SEARCH_BUILDINGS = "SEARCH_BUILDINGS";
export const GET_BUILDING = "GET_BUILDING";
export const GET_USER = "GET_USER";
// export const GET_COMMENT = "GET_COMMENT";
// export const ADD_COMMENT = "ADD_COMMENT";
// export const SET_LOADING = 'SET_LOADING';
// export const SET_ALERT = 'SET_ALERT';
// export const REMOVE_ALERT = 'REMOVE_ALERT';
